app = "solana-auto-sell-bot"
primary_region = "iad"

[build]

[env]
  NODE_ENV = "production"
  PORT = "3000"
  NODE_OPTIONS = "--max-old-space-size=4096 --unhandled-rejections=warn --max-http-header-size=32768"
  NEXT_TELEMETRY_DISABLED = "1"
  FORCE_COLOR = "0"
  NODE_NO_WARNINGS = "1"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  max_machines_running = 2

[[http_service.checks]]
  interval = "60s"
  timeout = "30s"
  grace_period = "60s"
  method = "GET"
  path = "/api/health"
  headers = { "User-Agent" = "fly-health-check" }

[[vm]]
  memory = "4gb"
  cpu_kind = "shared"
  cpus = 2

[deploy]
  release_command = "echo 'Deployment complete'"

kill_signal = "SIGTERM"
kill_timeout = "30s"
