app = "solana-auto-sell-bot"
primary_region = "iad"

[build]

[env]
  NODE_ENV = "production"
  PORT = "3000"
  NODE_OPTIONS = "--max-old-space-size=768"
  NEXT_TELEMETRY_DISABLED = "1"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[http_service.checks]]
  interval = "10s"
  timeout = "5s"
  grace_period = "10s"
  method = "GET"
  path = "/api/health"
  headers = { "User-Agent" = "fly-health-check" }

[machine]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1

[[services]]
  protocol = "tcp"
  internal_port = 3000

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

[deploy]
  release_command = "echo 'Deployment complete'"

[restart]
  policy = "on-failure"
  max_restarts = 3
  restart_delay = "5s"

[processes]
  app = "node server.js"

[logging]
  level = "info"
