app = "solana-auto-sell-bot"
primary_region = "iad"

[build]

[env]
  NODE_ENV = "production"
  PORT = "3000"
  NODE_OPTIONS = "--max-old-space-size=768"
  NEXT_TELEMETRY_DISABLED = "1"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[[http_service.checks]]
  interval = "15s"
  timeout = "10s"
  grace_period = "15s"
  method = "GET"
  path = "/api/health"
  headers = { "User-Agent" = "fly-health-check" }

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1

[deploy]
  release_command = "echo 'Deployment complete'"
